spring:
  main:
    allow-circular-references: true
  datasource:
    url: ${DATABASE_CONNECTION_URL:jdbc:mysql://localhost:3306/relationship?useSSL=false}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: update